INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЮУР', 'Южно-Уральская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЛАТ', 'Латвийская ж.д.', 'Латвия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('КБШ', 'Куйбышевская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('СВР', 'Свердловская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('БЕЛ', 'Белорусская ж.д.', 'Белоруссия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ОКТ', 'Октябрьская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('МСК', 'Московская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('СКВ', 'Северо-Кавказская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ГОР', 'Горьковская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЗАБ', 'Забайкальская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('КРС', 'Красноярская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЮЖН', 'Южная ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ПРВ', 'Приволжская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('КЗХ', 'Казахстанская ж.д.', 'Казахстан');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЗСБ', 'Западно-Сибрская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ВСБ', 'Восточно-Сибирская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('СЕВ', 'Северная ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('УТИ', 'Узбекские ж.д.', 'Узбекистан');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ТРК', 'Турецкая ж.д.', 'Турция');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ОДС', 'Одесская ж.д.', 'Украина');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ГРЗ', 'Грузинская ж.д.', 'Грузия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЮКЖД', 'Южно-Кавказская ж.д.', 'Армения');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЮВС', 'Юго-Восточная ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ДВС', 'Дальне-Восточная ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ДОН', 'Донецкая ж.д.', 'Украина');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('АЗР', 'Азербайджанская ж.д.', 'Азербайджан');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЮЗП', 'Юго-Западная ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('КРЫМ', 'Крымская ж. д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ТДЖ', 'Таджикистанская ж.д.', 'Таджикистан');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ФИН', 'Финские государственные ж. д.', 'Финляндия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ПДН', 'Приднепровская ж.д.', 'Приднестровье');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЛИТ', 'Литовская ж.д.', 'Литва');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('КРГ', 'Кыргызская ж.д.', 'Киргизия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ДВС', 'Дальневосточная ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('МНГ', 'Монгольская ж. д.', 'Монголия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЛЬВ', 'Львовская ж.д.', 'Украина');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ЭСТ', 'Эстонская ж.д.', 'Эстония');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('КАЛ', 'Калининградская ж.д.', 'Россия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ГЕР', 'Немецкая  ж. д.', 'Германия');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('РУМ', 'Румынская ж. д.', 'Румыния');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ИРАН', 'Иранская ж. д.', 'Иран');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ХАРБИН', 'Харбинская ж. д.', 'Китай');
INSERT INTO restapi.roads (road_name, road_fullname, country_of_road) VALUE ('ПОЛ', 'Польская ж. д.', 'Польша');